In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [93]:
df = pd.read_csv('Seasonal_Sales1.csv',encoding='unicode_escape')
df

,User_ID,Cust_name,Date,Gender,Product_ID,Platform,Age,Category,Amount,Zone,Occupation,Product_Category,State,Age Group,Marital_Status,Orders
0,1002903,Sanskriti,04-11-2023,F,P00125942,Ajio,28,Set,23952.0,Western,Healthcare,Auto,Maharashtra,26-35,0,1
1,1000732,Kartik,04-11-2023,F,P00110942,Myntra,35,kurta,23934.0,Southern,Govt,Auto,Andhra Pradesh,26-35,1,3
2,1001990,Bindu,04-12-2023,F,P00118542,Amazon,35,Western Dress,23924.0,Central,Automobile,Auto,Uttar Pradesh,26-35,1,3
3,1001425,Sudevi,04-12-2023,M,P00237842,Amazon,16,kurta,23912.0,Southern,Construction,Auto,Karnataka,0-17,0,2
4,1000588,Joni,04-12-2023,M,P00057942,Amazon,28,kurta,23877.0,Western,Food Processing,Auto,Gujarat,26-35,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11246,1000695,Manning,06-03-2022,M,P00296942,Meesho,19,Set,370.0,Western,Chemical,Office,Maharashtra,18-25,1,4
11247,1004089,Reichenbach,04-11-2023,M,P00171342,Myntra,33,Saree,367.0,Northern,Healthcare,Veterinary,Haryana,26-35,0,3
11248,1001209,Oshin,04-10-2023,F,P00201342,Ajio,40,Western Dress,213.0,Central,Textile,Office,Madhya Pradesh,36-45,0,4
11249,1004023,Noonan,04-09-2023,M,P00059442,Ajio,37,Western Dress,206.0,Southern,Agriculture,Office,Karnataka,36-45,0,3
11250,1002744,Brumley,04-05-2023,F,P00281742,Amazon,19,Top,188.0,Western,Healthcare,Office,Maharashtra,18-25,0,3

In [77]:
X = df.drop(['Platform','Category','Amount'],axis = 1)
X

,User_ID,Cust_name,Date,Gender,Product_ID,Age,Category,Amount,Zone,Occupation,Product_Category,State,Age Group,Marital_Status,Orders
0,1002903,Sanskriti,04-11-2023,F,P00125942,28,Set,23952.0,Western,Healthcare,Auto,Maharashtra,26-35,0,1
1,1000732,Kartik,04-11-2023,F,P00110942,35,kurta,23934.0,Southern,Govt,Auto,Andhra Pradesh,26-35,1,3
2,1001990,Bindu,04-12-2023,F,P00118542,35,Western Dress,23924.0,Central,Automobile,Auto,Uttar Pradesh,26-35,1,3
3,1001425,Sudevi,04-12-2023,M,P00237842,16,kurta,23912.0,Southern,Construction,Auto,Karnataka,0-17,0,2
4,1000588,Joni,04-12-2023,M,P00057942,28,kurta,23877.0,Western,Food Processing,Auto,Gujarat,26-35,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11246,1000695,Manning,06-03-2022,M,P00296942,19,Set,370.0,Western,Chemical,Office,Maharashtra,18-25,1,4
11247,1004089,Reichenbach,04-11-2023,M,P00171342,33,Saree,367.0,Northern,Healthcare,Veterinary,Haryana,26-35,0,3
11248,1001209,Oshin,04-10-2023,F,P00201342,40,Western Dress,213.0,Central,Textile,Office,Madhya Pradesh,36-45,0,4
11249,1004023,Noonan,04-09-2023,M,P00059442,37,Western Dress,206.0,Southern,Agriculture,Office,Karnataka,36-45,0,3
11250,1002744,Brumley,04-05-2023,F,P00281742,19,Top,188.0,Western,Healthcare,Office,Maharashtra,18-25,0,3

In [78]:
y = df['Platform']
y

0          Ajio
1        Myntra
2        Amazon
3        Amazon
4        Amazon
          ...
11246    Meesho
11247    Myntra
11248      Ajio
11249      Ajio
11250    Amazon
Name: Platform, Length: 11251, dtype: object

In [33]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() #clf = classification

In [ ]:
model.fit(X_train, y_train)

In [ ]:
accuracy = model.score(X_test,y_test)
print('Accuracy',accuracy)
result = model.predict(X_test)
result

In [73]:
df.reset_index()
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
le = LabelEncoder()
scaler = MinMaxScaler()

df = df['Platform'] = le.fit_transform(df['Platform'])
# print(dd)

# de=df.iloc[0:7,0:4]
# print(de)

scaler.fit_transform(df.iloc[:0:10])
df.iloc[:0:10] = scaler.fit_transform(df.iloc[:0:10])

X = df.drop(['Platform'],axis = 1)
y = df['Platform']
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Assuming X and y are your features and target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Evaluate the accuracy on the test set
accuracy = model.score(X_test, y_test)
print('Accuracy:', accuracy)

# Make predictions on new data
result = model.predict(X_test)
print(result)

AttributeError: 'numpy.ndarray' object has no attribute 'reset_index'

In [60]:
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Assuming df is your DataFrame
le = LabelEncoder()
df['Platform'] = le.fit_transform(df['Platform'])

scaler = MinMaxScaler()
X = df.drop(['Platform'], axis=1)
y = df['Platform']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create a Logistic Regression model
model = LogisticRegression()

# Train the model on the scaled training data
model.fit(X_train_scaled, y_train)

# Evaluate the accuracy on the scaled test set
accuracy = model.score(X_test_scaled, y_test)
print('Accuracy:', accuracy)

# Make predictions on new data
result = model.predict(X_test_scaled)
print(result)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [70]:
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Assuming df is your DataFrame
le = LabelEncoder()
df['Age'] = le.fit_transform(df['Age'])

scaler = MinMaxScaler()
X = df.drop(['Age'], axis=1)
y = df['Age']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create a Logistic Regression model
model = LogisticRegression()

# Train the model on the scaled training data
model.fit(X_train_scaled, y_train)

# Evaluate the accuracy on the scaled test set
accuracy = model.score(X_test_scaled, y_test)
print('Accuracy:', accuracy)

# Make predictions on new data
result = model.predict(X_test_scaled)
print(result)
array([1])
X_test.head(5)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [72]:
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Assuming df is your DataFrame
le = LabelEncoder()
df['Age'] = le.fit_transform(df['Age'])

scaler = MinMaxScaler()
X = df.drop(['Age'], axis=1)
y = df['Age']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create a Logistic Regression model
model = LogisticRegression()

# Train the model on the scaled training data
model.fit(X_train_scaled, y_train)

# Evaluate the accuracy on the scaled test set
accuracy = model.score(X_test_scaled, y_test)
print('Accuracy:', accuracy)

# Make predictions on new data
result = model.predict(X_test_scaled)
print(result)

# Reset the index of X_test before using head()
X_test_reset_index = X_test.reset_index(drop=True)

# Display the first 5 rows of X_test
print(X_test_reset_index.head(5))

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [74]:
df.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [75]:
df.columns()

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [79]:
df.shape

(11251, 16)

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  object
 2   Date              11251 non-null  object
 3   Gender            11251 non-null  object
 4   Product_ID        11251 non-null  object
 5   Platform          11251 non-null  object
 6   Age               11251 non-null  int64
 7   Category          11251 non-null  object
 8   Amount            11238 non-null  float64
 9   Zone              11251 non-null  object
 10  Occupation        11251 non-null  object
 11  Product_Category  11251 non-null  object
 12  State             11251 non-null  object
 13  Age Group         11251 non-null  object
 14  Marital_Status    11251 non-null  int64
 15  Orders            11251 non-null  int64
dtypes: float64(1), int64(4), object(11)
memory usage: 1.4+ MB

In [ ]:
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
le = LabelEncoder()
scaler = MinMaxScaler()

df = df['Platform'] = le.fit_transform(df['Platform'])
# print(dd)

# de=df.iloc[0:7,0:4]
# print(de)

scaler.fit_transform(df.iloc[:0:10])
df.iloc[:0:10] = scaler.fit_transform(df.iloc[:0:10])

X = df.drop(['User_ID','','','','','','','','','','',],axis = 1)
y = df['Platform']
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Assuming X and y are your features and target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Evaluate the accuracy on the test set
accuracy = model.score(X_test, y_test)
print('Accuracy:', accuracy)

# Make predictions on new data
result = model.predict(X_test)
print(result)

In [81]:
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
col_obj = df.select_dtypes(include = 'object').colunm

le = LabelEncoder()

# scaler = MinMaxScaler()
df[col_obj]=le.fit_transform(df[col_obj])
print(df)

# df = df['Platform'] = le.fit_transform(df['Platform'])
# # print(dd)

# # de=df.iloc[0:7,0:4]
# # print(de)

# scaler.fit_transform(df.iloc[:0:10])
# df.iloc[:0:10] = scaler.fit_transform(df.iloc[:0:10])

# X = df.drop(['User_ID','','','','','','','','','','',],axis = 1)
# y = df['Platform']
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score, classification_report

# # Assuming X and y are your features and target variable
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Create a Logistic Regression model
# model = LogisticRegression()

# # Train the model
# model.fit(X_train, y_train)

# # Evaluate the accuracy on the test set
# accuracy = model.score(X_test, y_test)
# print('Accuracy:', accuracy)

# # Make predictions on new data
# result = model.predict(X_test)
# print(result)

AttributeError: 'DataFrame' object has no attribute 'colunm'

In [91]:
# from sklearn.preprocessing import MinMaxScaler, LabelEncoder
# col_obj = df.select_dtypes(include = 'object').columns

# df.drop(['User_ID','Cust_name','Date','Product_ID','Age', 'Category','Amount','Zone','Occupation','Product_Category','State','Age Group','Marital_Status','Orders'],axis = 1)
df

# le = LabelEncoder()

# # scaler = MinMaxScaler()
# df[col_obj]=le.fit_transform(df[col_obj])
# print(df)

      Gender Platform
0          F     Ajio
1          F   Myntra
2          F   Amazon
3          M   Amazon
4          M   Amazon
...      ...      ...
11246      M   Meesho
11247      M   Myntra
11248      F     Ajio
11249      M     Ajio
11250      F   Amazon

[11251 rows x 2 columns]

In [94]:
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
le = LabelEncoder()
scaler = MinMaxScaler()

df = df['Platform'] = le.fit_transform(df['Platform'])
# print(dd)

# de=df.iloc[0:7,0:4]
# print(de)

scaler.fit_transform(df.iloc[:0:10])
df.iloc[:0:10] = scaler.fit_transform(df.iloc[:0:10])

X = df.drop([''],axis = 1)
y = df['Platform']
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Assuming X and y are your features and target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Evaluate the accuracy on the test set
accuracy = model.score(X_test, y_test)
print('Accuracy:', accuracy)

# Make predictions on new data
result = model.predict(X_test)
print(result)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, classification_report


df = pd.read_csv('Seasonal_Sales1.csv',encoding='unicode_escape')
# Data Cleaning

print(df.isnull().sum())
num_col = df.select_dtypes(include="number").columns
print(num_col)
df.fillna(df[num_col].mean(), inplace=True)
print(df.isnull().sum())


print('Duplicate Rows :' , df.duplicated().sum())
df = df.drop_duplicates()
print('Duplicate Rows :' , df.duplicated().sum())



df = df.drop(columns=['User_ID','Cust_name','Date','Product_Category','State','Age Group','Orders'])
print(df)

print(df.isnull().sum())
num_col = df.select_dtypes(include="number").columns
print(num_col)
df.fillna(df[num_col].mean(), inplace=True)
print(df.isnull().sum())


print('Duplicate Rows :' , df.duplicated().sum())
df = df.drop_duplicates()
print('Duplicate Rows :' , df.duplicated().sum())
le = LabelEncoder()
scaler = MinMaxScaler()

col_obj = df.select_dtypes(include = 'object').columns
col_num = df.select_dtypes(include = 'number').columns
print(col_obj)

#categories encoding
df['Gender']=le.fit_transform(df['Gender'])
df['Category']=le.fit_transform(df['Category'])
df['Platform']=le.fit_transform(df['Platform'])
df['Zone']=le.fit_transform(df['Zone'])
df['Occupation']=le.fit_transform(df['Occupation'])

#number values scaling

df['Age'] = scaler.fit_transform(df[['Age']])
df['Amount'] = scaler.fit_transform(df[['Amount']])


X = df.drop(columns='Platform')
Y = df['Platform']

X_train, x_test, Y_train, y_test = train_test_split(X, Y, test_size=0.25)

model = LogisticRegression()
model.fit(X_train,Y_train)



prediction =  model.predict(x_test)
accuracy = accuracy_score(y_test, prediction)
report = classification_report(y_test , prediction)

print("Accuracy : ",f"{(accuracy*100):.2f}" ,"%")
print("Classification Report :\n" , report)

print(df)

User_ID              0
Cust_name            0
Date                 0
Gender               0
Product_ID           0
Platform             0
Age                  0
Category             0
Amount              13
Zone                 0
Occupation           0
Product_Category     0
State                0
Age Group            0
Marital_Status       0
Orders               0
dtype: int64
Index(['User_ID', 'Age', 'Amount', 'Marital_Status', 'Orders'], dtype='object')
User_ID             0
Cust_name           0
Date                0
Gender              0
Product_ID          0
Platform            0
Age                 0
Category            0
Amount              0
Zone                0
Occupation          0
Product_Category    0
State               0
Age Group           0
Marital_Status      0
Orders              0
dtype: int64
Duplicate Rows : 0
Duplicate Rows : 0
      Gender Product_ID Platform  Age       Category   Amount      Zone  \
0          F  P00125942     Ajio   28            Set  23952.0   Western
1          F  P00110942   Myntra   35          kurta  23934.0  Southern
2          F  P00118542   Amazon   35  Western Dress  23924.0   Central
3          M  P00237842   Amazon   16          kurta  23912.0  Southern
4          M  P00057942   Amazon   28          kurta  23877.0   Western
...      ...        ...      ...  ...            ...      ...       ...
11246      M  P00296942   Meesho   19            Set    370.0   Western
11247      M  P00171342   Myntra   33          Saree    367.0  Northern
11248      F  P00201342     Ajio   40  Western Dress    213.0   Central
11249      M  P00059442     Ajio   37  Western Dress    206.0  Southern
11250      F  P00281742   Amazon   19            Top    188.0   Western

            Occupation  Marital_Status
0           Healthcare               0
1                 Govt               1
2           Automobile               1
3         Construction               0
4      Food Processing               1
...                ...             ...
11246         Chemical               1
11247       Healthcare               0
11248          Textile               0
11249      Agriculture               0
11250       Healthcare               0

[11251 rows x 9 columns]
Gender            0
Product_ID        0
Platform          0
Age               0
Category          0
Amount            0
Zone              0
Occupation        0
Marital_Status    0
dtype: int64
Index(['Age', 'Amount', 'Marital_Status'], dtype='object')
Gender            0
Product_ID        0
Platform          0
Age               0
Category          0
Amount            0
Zone              0
Occupation        0
Marital_Status    0
dtype: int64
Duplicate Rows : 5
Duplicate Rows : 0
Index(['Gender', 'Product_ID', 'Platform', 'Category', 'Zone', 'Occupation'], dtype='object')

ValueError: could not convert string to float: 'P00120042'

In [99]:
sales_state = df.groupby(['State'],as_index=False)['Orders'].sum().sort_values(by='Orders',ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'State',y ='Orders')

KeyError: 'State'